### ISSUE TITLE
Limit the height of the quickhelp menu

### ISSUE THREAD

**Issue by fniessen** [expez/company-quickhelp#3]
Hello. Could it be possible to get a variable to set the max height of the quick help (for example, to 10 lines -- such as the max height of my Company menu)?

Thanks in advance!

**Comment by expez** [comment]
That's a great idea, thanks for the suggestion!

I've pushed a fix to to a topic branch, with an associated PR into master.  I'm hesitating in merging it in because I ran into #2 quite a few times while testing this. 

Do you have time to try that branch and see if the popup appears with an offset that's too large?

**Comment by fniessen** [comment]
Thanks for adding this.

I think you can merge it, because it must be completely independant of bug #2 which I got quite often since using Company-quickhelp. I even wanted to report it, but I saw it already was, and I have no recipe to reproduce it... I still don't understand when it happens or when it stops from happening...

**Comment by expez** [comment]
@fniessen Could you provide any details about where you experienced #2?  Which backend(s)?  I've spent hours trying to find the problem.  It's really killing me :p

**Comment by fniessen** [comment]
Lars Andersen wrote:

> @fniessen Could you provide any details about where you experienced #2?  Which
> backend(s)?  I've spent hours trying to find the problem.  It's really killing
> me :p

DONE. See #2.
